import torch
import torch.nn as nn
import torch_geometric as tg
from torch_geometric.data import Data
from torch_geometric.datasets import Planetoid
import torch.nn.functional as F
from torch_geometric.nn import MessagePassing
from torch_geometric.utils import add_self_loops, degree
# from torch_geometric.nn import GCNConv
from torch.nn import init
from torch_scatter import scatter_mean
import pdb

import pdb

####################### NNs #############################


class EGNN(torch.nn.Module):
    def __init__(self, input_dim, feature_dim, hidden_dim, output_dim,
                 feature_pre=True, layer_num=2, dropout=True, **kwargs):
        super(EGNN, self).__init__()
        self.feature_pre = feature_pre
        self.layer_num = layer_num
        self.dropout = dropout
        if feature_pre:
            self.linear_pre = nn.Linear(input_dim, feature_dim)
            self.conv_first = SAGEConvEGNN(feature_dim, hidden_dim)
        else:
            self.conv_first = SAGEConvEGNN(input_dim, hidden_dim)
        self.conv_hidden = nn.ModuleList([SAGEConvEGNN(hidden_dim, hidden_dim) for i in range(layer_num - 2)])
        self.conv_out = SAGEConvEGNN(hidden_dim, output_dim)

    def forward(self, data):
        x, edge_index, edge_attr = data.x, data.edge_index, data.edge_attr
        if self.feature_pre:
            x = self.linear_pre(x)
        x = self.conv_first(x, edge_index, edge_attr)
        x = F.relu(x)
        if self.dropout:
            x = F.dropout(x, training=self.training)
        for i in range(self.layer_num-2):
            x = self.conv_hidden[i](x, edge_index, edge_attr)
            x = F.relu(x)
            if self.dropout:
                x = F.dropout(x, training=self.training)
        x = self.conv_out(x, edge_index, edge_attr)
        x = F.normalize(x, p=2, dim=-1)
        return x

class SAGEConvEGNN(tg.nn.MessagePassing):
    r"""The GraphSAGE operator from the `"Inductive Representation Learning on
    Large Graphs" <https://arxiv.org/abs/1706.02216>`_ paper

    .. math::
        \mathbf{\hat{x}}_i &= \mathbf{\Theta} \cdot
        \mathrm{mean}_{j \in \mathcal{N(i) \cup \{ i \}}}(\mathbf{x}_j)

        \mathbf{x}^{\prime}_i &= \frac{\mathbf{\hat{x}}_i}
        {\| \mathbf{\hat{x}}_i \|_2}.

    Args:
        in_channels (int): Size of each input sample.
        out_channels (int): Size of each output sample.
        normalize (bool, optional): If set to :obj:`True`, output features
            will be :math:`\ell_2`-normalized. (default: :obj:`False`)
        concat (bool, optional): If set to :obj:`True`, will concatenate
            current node features with aggregated ones. (default: :obj:`False`)
        bias (bool, optional): If set to :obj:`False`, the layer will not learn
            an additive bias. (default: :obj:`True`)
        **kwargs (optional): Additional arguments of
            :class:`torch_geometric.nn.conv.MessagePassing`.
    """
    def __init__(self, in_channels, out_channels, normalize=False,
                 concat=True, bias=True, **kwargs):
        super(SAGEConvEGNN, self).__init__(aggr='mean', **kwargs)

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.normalize = normalize
        self.concat = concat

        in_channels = 2 * in_channels if concat else in_channels
        self.weight = torch.nn.Parameter(torch.Tensor(in_channels, out_channels))

        if bias:
            self.bias = torch.nn.Parameter(torch.Tensor(out_channels))
        else:
            self.register_parameter('bias', None)

        self.reset_parameters()

    def reset_parameters(self):
        torch.nn.init.uniform_(self.bias, -1, 1)
        torch.nn.init.uniform_(self.weight, -1, 1)
        # uniform(self.weight.size(0), self.weight)
        # uniform(self.weight.size(0), self.bias)

    def forward(self, x, edge_index, edge_attr, size=None):
        """
        Args:
            res_n_id (Tensor, optional): Residual node indices coming from
                :obj:`DataFlow` generated by :obj:`NeighborSampler` are used to
                select central node features in :obj:`x`.
                Required if operating in a bipartite graph and :obj:`concat` is
                :obj:`True`. (default: :obj:`None`)
        """
        # if not self.concat and torch.is_tensor(x):
        #     edge_index, _ = remove_self_loops(edge_index)
        #     edge_index = add_self_loops(edge_index, num_nodes=x.size(0))
            # edge_index, edge_weight = add_remaining_self_loops(
            #     edge_index, edge_weight, 1, x.size(self.node_dim))

        return self.propagate(edge_index, size=size, x=x,
                              edge_attr=edge_attr)


    def message(self, x_j, edge_attr):
        # print(edge_attr.shape)
        # print(x_j.shape)
        emb = torch.stack([x_j]*edge_attr.shape[1], dim=0)
        edge_attr_aux = edge_attr.permute(1,0)
        # print(emb.shape)
        # Y = edge_attr_aux @ emb
        for i in range(emb.shape[0]):
            emb[i] = emb[i]*edge_attr[:,i].unsqueeze(1).float()

        # Multi-edge agreggation
        if self.concat:
            emb = torch.cat(torch.unbind(emb, dim=0), dim=-1)
        else:
            emb = torch.mean(emb, 0)

        return emb

    def update(self, aggr_out, x):
        aggr_out = torch.matmul(aggr_out, self.weight)

        if self.bias is not None:
            aggr_out = aggr_out + self.bias

        if self.normalize:
            aggr_out = F.normalize(aggr_out, p=2, dim=-1)

        return aggr_out

    def __repr__(self):
        return '{}({}, {})'.format(self.__class__.__name__, self.in_channels,
                                   self.out_channels)